// Auto-generated by stellar-contracts-kit
// Contract : CBN6DV6AOZWNROEXKYWJGZLV2LODUE4LIQTVDJWYXDUH6K7X2XHIW5RL
// Network  : testnet
// Re-run `npx sck generate` to update after a contract upgrade.

import type { ContractMethodFn } from 'stellar-contracts-kit'

// Custom Types

export interface Order {
  buyer: string
  id: bigint
  listing_id: bigint
  seller: string
  timestamp: bigint
  total: bigint
}

export interface Listing {
  active: boolean
  category: string
  created_at: bigint
  description: string
  id: bigint
  price: bigint
  seller: string
  title: string
}

// Contract Interface

export interface Marketplace {
  buy_item: ContractMethodFn<void, [buyer: string, id: bigint]>
  list_item: ContractMethodFn<bigint, [seller: string, category: string, title: string, description: string, price: bigint]>
  get_orders: ContractMethodFn<Array<Order>, [listing_id: bigint]>
  initialize: ContractMethodFn<void, [token: string]>
  cancel_item: ContractMethodFn<void, [seller: string, id: bigint]>
  get_listing: ContractMethodFn<Listing, [id: bigint]>
  update_item: ContractMethodFn<void, [seller: string, id: bigint, category: string, title: string, description: string, price: bigint]>
  get_listings: ContractMethodFn<Array<Listing>, []>
  get_my_listings: ContractMethodFn<Array<Listing>, [caller: string]>
  get_active_listings: ContractMethodFn<Array<Listing>, []>
}

export const CONTRACT_ID = 'CBN6DV6AOZWNROEXKYWJGZLV2LODUE4LIQTVDJWYXDUH6K7X2XHIW5RL' as const
