// Auto-generated by stellar-contracts-kit
// Example usage for Contract
// Contract : CACQRTEGIEFK7JURNBXXKPZLLRQ44MPQKXWNSUNQUNJGTPLE2PXAMG4Q
// Network  : testnet
// Adapt this file to your project. Re-run `npx sck generate` to refresh after a contract upgrade.

import { StellarContractsKit } from 'stellar-contracts-kit'
// Types file: ./contracts/contract.ts. Update the path below if using snippets elsewhere.
import type { Contract } from './contract.js'
import { CONTRACT_ID } from './contract.js'

const kit = new StellarContractsKit({ network: 'testnet' })

// Connect wallet (opens picker modal if no wallet specified)
const { address } = await kit.connect()
console.log('Connected:', address)

// Load the typed contract client
const contract = await kit.contract<Contract>(CONTRACT_ID)

// buy_item(buyer: string, id: bigint) -> void
const { txHash: buy_itemTxHash } = await contract.buy_item.invoke(
  'G...',  // buyer: string
  0n,  // id: bigint
)
console.log('buy_item txHash:', buy_itemTxHash)

// list_item(seller: string, category: string, title: string, description: string, file_link: string, price: bigint) -> bigint
const { txHash: list_itemTxHash, result: list_itemResult } = await contract.list_item.invoke(
  'G...',  // seller: string
  '',  // category: string
  '',  // title: string
  '',  // description: string
  '',  // file_link: string
  0n,  // price: bigint
)
console.log('list_item txHash:', list_itemTxHash, 'result:', list_itemResult)

// get_orders(listing_id: bigint) -> Array<Order>
const { txHash: get_ordersTxHash, result: get_ordersResult } = await contract.get_orders.invoke(
  0n,  // listing_id: bigint
)
console.log('get_orders txHash:', get_ordersTxHash, 'result:', get_ordersResult)

// initialize(token: string) -> void
const { txHash: initializeTxHash } = await contract.initialize.invoke(
  'G...',  // token: string
)
console.log('initialize txHash:', initializeTxHash)

// cancel_item(seller: string, id: bigint) -> void
const { txHash: cancel_itemTxHash } = await contract.cancel_item.invoke(
  'G...',  // seller: string
  0n,  // id: bigint
)
console.log('cancel_item txHash:', cancel_itemTxHash)

// get_listing(id: bigint) -> Listing
const { txHash: get_listingTxHash, result: get_listingResult } = await contract.get_listing.invoke(
  0n,  // id: bigint
)
console.log('get_listing txHash:', get_listingTxHash, 'result:', get_listingResult)

// update_item(seller: string, id: bigint, category: string, title: string, description: string, price: bigint) -> void
const { txHash: update_itemTxHash } = await contract.update_item.invoke(
  'G...',  // seller: string
  0n,  // id: bigint
  '',  // category: string
  '',  // title: string
  '',  // description: string
  0n,  // price: bigint
)
console.log('update_item txHash:', update_itemTxHash)

// get_listings() -> Array<Listing>
const { result: get_listingsResult } = await contract.get_listings.read()
console.log('get_listings:', get_listingsResult)

// get_my_listings(caller: string) -> Array<Listing>
const { txHash: get_my_listingsTxHash, result: get_my_listingsResult } = await contract.get_my_listings.invoke(
  'G...',  // caller: string
)
console.log('get_my_listings txHash:', get_my_listingsTxHash, 'result:', get_my_listingsResult)

// get_active_listings() -> Array<Listing>
const { result: get_active_listingsResult } = await contract.get_active_listings.read()
console.log('get_active_listings:', get_active_listingsResult)
